### ISSUE TITLE
"Кастомные" стили

### ISSUE THREAD

**Issue by starkovsky** [Krausso/Openweather-vue#5]
https://github.com/Krausso/Openweather-vue/blob/299501aea491109ae875a634a269c32ef793512b/src/assets/custom.scss#L1

Вы же сами пишите комментарий к какому компоненту вы назначаете стиль, ему не место в абстрактном файле, положите обратно в SFC в блоке `<style></style>`

**Comment by Krausso** [comment]
Сделал
